- hosts: all
  vars:
    dev: /dev/sda
    vg_name: ubuntu-vg
    lv_name: root
  tasks:
  - name: Get partition information
    parted:
      device: "{{dev}}"
    register: partinfo
    become: yes
  - debug: var=partinfo.partitions[-1].end
  - name: "Create a new partition after {{partinfo.partitions[-1].end}}KiB"
    parted:
      part_start: "{{partinfo.partitions[1].end}}KiB"
      device: "{{dev}}"
      number: "3"
      flags: [ lvm ]
      state: present
    become: yes
  - name: Probe kernel about partition table changes
    command: partprobe
    become: yes
  - name: Add the partition to the volume group
    lvg:
      vg: "{{vg_name}}"
      pvs: "{{dev}}{{partinfo.partitions[-1].num}},{{dev}}3"
    become: yes
  - name: Extend LVM to the whole volume group
    lvol:
      vg: "{{vg_name}}"
      lv: "{{lv_name}}"
      size: +100%FREE
    become: yes
  - name: Extend the filesystem
    filesystem:
      fstype: ext4
      dev: "/dev/mapper/ubuntu--vg-{{lv_name}}"
      resizefs: yes
    become: yes
